#Requires -Version 7
<#
.SYNOPSIS
    Decompiles Human Host's game assemblies into HumanHostCodebase\ for reference.

.DESCRIPTION
    Runs ilspycmd on each assembly in "Human Host_Data\Managed" and writes one
    project folder per assembly. The game ships PDBs, so local variable names are
    kept (-usepdb).

    Human Host's own code is split across many assemblies (Player, Creature,
    Build_System, Mgr_Hub, SaveData, ...), not just Assembly-CSharp. The default
    set is those developer-named assemblies. -All adds every other non-framework
    assembly (Asset Store packages such as FinalIK, A* Pathfinding, EasySave).

    Output is gitignored in the main repository: it is copyrighted game code.
    Unless -NoGit is given, HumanHostCodebase\ is kept as its own local Git
    repository with one commit per game build, so `git diff` shows what changed
    between game updates.

    Requires ilspycmd: dotnet tool install -g ilspycmd

.EXAMPLE
    .\tools\Decompile-GameCode.ps1
    .\tools\Decompile-GameCode.ps1 -Assemblies Player,Creature
    .\tools\Decompile-GameCode.ps1 -All
#>
[CmdletBinding()]
param(
    [string]$GameDir,
    [string]$OutputPath,
    [string[]]$Assemblies,
    [switch]$All,
    [switch]$NoGit,
    [int]$ThrottleLimit = 4
)

$ErrorActionPreference = 'Stop'
. "$PSScriptRoot\Common.ps1"

$GameAssemblies = @(
    'AI', 'Assembly-CSharp', 'Bicycle', 'Bicycle_Glue', 'BloodFunc', 'Build_System',
    'Camera', 'Car', 'Circular_Bar', 'Creature', 'Editor_Tooltip', 'Equipment',
    'Fast_Light', 'File_Verification', 'G_Save', 'GameSettings', 'Global_Funcs',
    'Hand_Tools', 'Item_Info', 'Language', 'Merchant', 'Mgr_Hub', 'MyEditor', 'My_Pool',
    'Notifications', 'Optimize', 'Player', 'Player_HotKeys', 'Process_BI',
    'Refs_KeepAlive', 'Rich_FX', 'RotaryDebug', 'SaveData', 'ScreenDamage',
    'Shader_Warm', 'Sound_FX', 'StartScene', 'Static_Class', 'SteamManager',
    'Sun_Flares', 'Terrain', 'Trap', 'UI', 'UIResource', 'Use_F', 'Visual',
    'Weather', 'xLua_DF'
)
$FrameworkPattern = '^(System|Mono\.|mscorlib$|netstandard$|Microsoft\.|UnityEngine|Unity\.|Sentry)'

if (-not (Get-Command ilspycmd -ErrorAction SilentlyContinue)) {
    throw 'ilspycmd not found. Install it with: dotnet tool install -g ilspycmd'
}

$GameDir = Resolve-HumanHostDir -GameDir $GameDir
$managed = Join-Path $GameDir 'Human Host_Data\Managed'
if (-not $OutputPath) { $OutputPath = Join-Path $script:RepoRoot 'HumanHostCodebase' }
New-Item -ItemType Directory -Force $OutputPath | Out-Null
$OutputPath = (Resolve-Path $OutputPath).Path

$names = if ($Assemblies) {
    $Assemblies
} elseif ($All) {
    Get-ChildItem $managed -Filter *.dll | ForEach-Object BaseName | Where-Object { $_ -notmatch $FrameworkPattern }
} else {
    $GameAssemblies
}

$missing = $names | Where-Object { -not (Test-Path (Join-Path $managed "$_.dll")) }
if ($missing) { Write-Warning "Not found in Managed, skipped: $($missing -join ', ')" }
$names = $names | Where-Object { $_ -notin $missing }

$refDirs = @($managed, (Join-Path $GameDir 'BepInEx\core')) | Where-Object { Test-Path $_ }
Write-Host "Decompiling $($names.Count) assemblies to $OutputPath"

$results = $names | ForEach-Object -ThrottleLimit $ThrottleLimit -Parallel {
    $name = $_
    $dll = Join-Path $using:managed "$name.dll"
    $out = Join-Path $using:OutputPath $name
    if (Test-Path $out) { Remove-Item -LiteralPath $out -Recurse -Force }
    $argList = @('-p', '-o', $out, '--nested-directories', '--disable-updatecheck')
    if (Test-Path ([IO.Path]::ChangeExtension($dll, '.pdb'))) { $argList += '-usepdb' }
    foreach ($r in $using:refDirs) { $argList += @('-r', $r) }
    $log = & ilspycmd @argList $dll 2>&1
    [pscustomobject]@{ Name = $name; ExitCode = $LASTEXITCODE; Log = ($log | Select-Object -Last 3) -join ' ' }
}

$failed = @($results | Where-Object ExitCode -ne 0)
foreach ($f in $failed) { Write-Warning "$($f.Name) failed: $($f.Log)" }

$build = ''
$manifest = Join-Path $GameDir "..\..\appmanifest_$($script:HumanHostAppId).acf"
if (Test-Path $manifest) {
    $build = (Select-String -Path $manifest -Pattern '"buildid"\s+"(\d+)"').Matches[0].Groups[1].Value
}
$ilspyVersion = (& ilspycmd --version | Select-Object -First 1)

@"
# Human Host decompiled reference

Generated by tools/Decompile-GameCode.ps1. Do not edit or redistribute.

- Steam build ID: $build
- Assembly-CSharp.dll timestamp: $((Get-Item (Join-Path $managed 'Assembly-CSharp.dll')).LastWriteTime.ToString('u'))
- Decompiler: $ilspyVersion
- Assemblies: $($names.Count - $failed.Count) of $($names.Count) succeeded
"@ | Set-Content -Encoding utf8 (Join-Path $OutputPath 'BUILD_INFO.md')

if (-not $NoGit) {
    Push-Location $OutputPath
    try {
        if (-not (Test-Path '.git')) { git init --quiet }
        git add -A
        git diff --cached --quiet
        if ($LASTEXITCODE -ne 0) {
            git commit --quiet -m "Human Host build $build"
            Write-Host "Committed snapshot for build $build in $OutputPath (local only)."
        } else {
            Write-Host 'No changes since the last snapshot.'
        }
    } finally {
        Pop-Location
    }
}

Write-Host "Done: $($names.Count - $failed.Count) succeeded, $($failed.Count) failed."
if ($failed.Count) { exit 1 }
